### ISSUE TITLE
Missing data file in sdist tarball for test suite

### ISSUE THREAD

**Issue by snoyberg** [stschiff/sequence-formats#1]
Running the test suite for 1.5.1 on the Stackage build server, I see the error message:

    Failures:

      test/SequenceFormats/PlinkSpec.hs:57:5:
      1) SequenceFormats.Plink.readFamFile should read a FAM file correctly
           uncaught exception: IOException of type NoSuchThing
           testDat/example.fam: openFile: does not exist (No such file or directory)

      To rerun use: --match "/SequenceFormats.Plink/readFamFile/should read a FAM file correctly/"

      test/SequenceFormats/PlinkSpec.hs:62:5:
      2) SequenceFormats.Plink.readBedFile should read genotypes correctly
           uncaught exception: IOException of type NoSuchThing
           testDat/example.plink.bed: openFile: does not exist (No such file or directory)

      To rerun use: --match "/SequenceFormats.Plink/readBedFile/should read genotypes correctly/"

**Comment by stschiff** [comment]
Sorry, forgot to include the new test files into the cabal package. Fixed in 1.5.1.1. Should work now.

I sincerely hope you create these feedbacks automatically. It's an amazing service and I appreciate all the time that goes into curating stackage!

**Comment by snoyberg** [comment]
That's very kind, thank you! And thank you for the super quick fix.
