### ISSUE TITLE
Ord GenoEntry

### ISSUE THREAD

**Issue by nevrome** [stschiff/sequence-formats#2]
Could `GenoEntry` become an instance of `Ord`? There are some applications where I want to call `sort` + `group` on it (e.g. allele frequency). So far I'm defining my own instance with

```haskell
instance Ord GenoEntry where
    compare Het x = case x of
        Het     -> EQ
        _       -> LT
    compare HomRef x = case x of
        Het     -> GT
        HomRef  -> EQ
        _       -> LT
    compare HomAlt x = case x of
        Het     -> GT
        HomRef  -> GT
        HomAlt  -> EQ
        _       -> LT
    compare Missing x = case x of
        Missing -> EQ
        _       -> GT
```
But that is tedious and the orphaned instance makes the pedantic compiler unhappy.

Maybe there is an entirely different solution to this?

**Comment by stschiff** [comment]
I'm skeptical. If there is a natural ordering to something, then `Ord` makes sense, but if not, it feels weird. This is a case where `sortBy` and `groupBy` make a lot more sense, in my view. 

If I interpret your case above correctly, you'd like to impose an ordering `Het < HomRef < HomAlt < Missing` which doesn't make sense to me at all. If anything, you'd like to order by non-reference dosage (`HomRef < Het < HomAlt`), but what do you do with missing?

**Comment by nevrome** [comment]
Alright - you have a point. On the other hand there is no disadvantage to attaching an arbitrary order? You loose nothing, but win a more simple sort/group by construct.

I went for this workaround now:

```Haskell
sortBy compareGenoEntry xs

compareGenoEntry :: GenoEntry -> GenoEntry -> Ordering
compareGenoEntry Het x = case x of
    Het     -> EQ
    _       -> LT
compareGenoEntry HomRef x = case x of
    Het     -> GT
    HomRef  -> EQ
    _       -> LT
compareGenoEntry HomAlt x = case x of
    Het     -> GT
    HomRef  -> GT
    HomAlt  -> EQ
    _       -> LT
compareGenoEntry Missing x = case x of
    Missing -> EQ
    _       -> GT
```

**Comment by stschiff** [comment]
Or

```
compareGenoEntry x y = compare (g2n x) (g2n y)
  where
    g2n HomRef = 1
    g2n Het = 2
    g2n HomAlt = 3
    g2n Missing = 4
```

**Comment by nevrome** [comment]
Wow - this is brilliant! Scales much better!
